language: ruby
script:
  - bundle exec rspec
notifications:
  slack:
    secure: jEpErw3R+xC1o/KBRi5tJd/wocuE0IMr1ua6YL6E5JWaFCcGwaQJNZ9oMCJbCplJ3F5o4fFoEXiDKd+9IkFil3UQMtgOfVzDh4t5fgIPSFFiNo22xRB75NSQmf9GXOsBr6/QQODK8U7CKaI53BaZjHon0lPVaNOTtNMZNbLlxUDls8Exmi+Wliar6QXsRBmFvSt1t3WhEx6rNWexxyDCRrSRKzw43fBh7Ehf2f7QmZ1jqn4f5wreJbxWP/Htp6Ae26JCEw9Tqzg2dKycu2CGbdoYrDTvk04fy1REymDpAjXYHgcJkpTjeM+GFyGfLw/ls6DcdBG9Ge4wvTmCAnUHTZ6Olx4oG82VWA73ez3XxhrnsVWZeKKr1JMnkYyO5BP7L0xcxIE0QkpHuAzrZzBkMV9hfc2/44VIblP6aeHlZuec+OE5alPIqzw6rzRGR8QwFbQwd/dSgHBUV6aLZeakpYyyo0OuxRyiSAJjMfsM9pg7i/KaBZk00VXpLdbIUcVmnCqjoVyLMFhrHeic9gbB72t+yz/RV9h5nUgtrrV/ZSwpvfa5pOIr1SHO3T0Go4rgTbrRs3gwwhHCBNdF04ePcrUzAC6WhN6ns/WM8BE+gl57iHK2cXh7JGKfA7sPpeeBddsBW7B9udrX2EJl37YhBp9aAj5SHeNnJ/Urc1QQ2p8=
