default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development: 
  <<: *default
  database: web-stgn-posts_development

test: 
  <<: *default
  database: web-stgn-posts_test

production:
  <<: *default
  database: fast-refuge-62440_production
  username: fast-refuge-62440
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>

